
services:
  db:
    image: postgres:16
    container_name: marketplace_db
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    container_name: marketplace_migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command: [
        '-path=/migrations',
        '-database',
        'postgres://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}?sslmode=disable',
        'up'
      ]
    restart: on-failure

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketplace_api
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    env_file: .env
    environment:
      - DB_DSN=postgres://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}?sslmode=disable
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  db-data:
