basePath: /v1
definitions:
  dto.AdResponse:
    properties:
      author_login:
        type: string
      created_at:
        type: string
      id:
        type: integer
      image_url:
        type: string
      is_owner:
        type: boolean
      price:
        type: integer
      text:
        type: string
      title:
        type: string
      user_id:
        type: integer
    type: object
  dto.UserResponse:
    properties:
      created_at:
        type: string
      id:
        type: integer
      login:
        type: string
    type: object
  handlers.AdRequest:
    properties:
      image_url:
        type: string
      price:
        type: integer
      text:
        type: string
      title:
        type: string
    type: object
  handlers.LoginRequest:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  handlers.RegistrationRequest:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a simple marketplace API.
  title: Marketplace API
  version: "1.0"
paths:
  /ads:
    get:
      description: Returns a list of ads with pagination and filtering.
      parameters:
      - description: Sort by field (price or created_at)
        enum:
        - price
        - created_at
        in: query
        name: sort_by
        type: string
      - description: Sort order (asc or desc)
        enum:
        - asc
        - desc
        in: query
        name: order
        type: string
      - description: Page number (1-based)
        in: query
        name: page
        type: integer
      - description: Number of items per page (max 100)
        in: query
        name: limit
        type: integer
      - description: Minimum price filter
        in: query
        name: min_price
        type: integer
      - description: Maximum price filter
        in: query
        name: max_price
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.AdResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: List ads
      tags:
      - ads
    post:
      consumes:
      - application/json
      description: Creates a new ad for the authenticated user.
      parameters:
      - description: Ad Info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.AdRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              format: int64
              type: integer
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Create a new ad
      tags:
      - ads
  /login:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns a JWT token.
      parameters:
      - description: Login Credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Log in a user
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      description: Creates a new user and returns their ID.
      parameters:
      - description: Registration Info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.RegistrationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Conflict
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
